USE [boksys_SampleDB]
GO

/****** Object:  Table [dbo].[MASTER_ACCOUNT_TABLE]    Script Date: 12/30/2023 7:38:27 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MASTER_ACCOUNT_TABLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AccountNumber] [int] NOT NULL,
	[AccountCode] [nvarchar](50) NULL,
	[AccountName] [nvarchar](max) NOT NULL,
	[Description] [nvarchar](max) NULL,
	[isCategory] [int] NOT NULL,
	[isType] [int] NOT NULL,
	[isMainAccount] [int] NOT NULL,
	[isSubAccount] [int] NOT NULL,
	[isStatement] [int] NOT NULL,
	[CreatedBy] [int] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedBy] [int] NOT NULL,
	[ModifiedDate] [datetime] NULL,
	[isEnabled] [int] NOT NULL,
	[Remarks] [nvarchar](max) NULL,
 CONSTRAINT [PK_MASTER_ACCOUNT_TABLE] PRIMARY KEY CLUSTERED 
(
	[AccountNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[MASTER_ACCOUNT_TABLE] ADD  CONSTRAINT [DF_MASTER_ACCOUNT_TABLE_AccountNumber]  DEFAULT ((0)) FOR [AccountNumber]
GO

ALTER TABLE [dbo].[MASTER_ACCOUNT_TABLE] ADD  CONSTRAINT [DF_MASTER_ACCOUNT_TABLE_isCategory]  DEFAULT ((0)) FOR [isCategory]
GO

ALTER TABLE [dbo].[MASTER_ACCOUNT_TABLE] ADD  CONSTRAINT [DF_MASTER_ACCOUNT_TABLE_isType]  DEFAULT ((0)) FOR [isType]
GO

ALTER TABLE [dbo].[MASTER_ACCOUNT_TABLE] ADD  CONSTRAINT [DF_MASTER_ACCOUNT_TABLE_isMainAccount]  DEFAULT ((0)) FOR [isMainAccount]
GO

ALTER TABLE [dbo].[MASTER_ACCOUNT_TABLE] ADD  CONSTRAINT [DF_Table_1_isSub-Account]  DEFAULT ((0)) FOR [isSubAccount]
GO

ALTER TABLE [dbo].[MASTER_ACCOUNT_TABLE] ADD  CONSTRAINT [DF_MASTER_ACCOUNT_TABLE_isStatement]  DEFAULT ((0)) FOR [isStatement]
GO

ALTER TABLE [dbo].[MASTER_ACCOUNT_TABLE] ADD  CONSTRAINT [DF_MASTER_ACCOUNT_TABLE_CreatedBy]  DEFAULT ((-1)) FOR [CreatedBy]
GO

ALTER TABLE [dbo].[MASTER_ACCOUNT_TABLE] ADD  CONSTRAINT [DF_MASTER_ACCOUNT_TABLE_CreatedDate]  DEFAULT (getdate()) FOR [CreatedDate]
GO

ALTER TABLE [dbo].[MASTER_ACCOUNT_TABLE] ADD  CONSTRAINT [DF_MASTER_ACCOUNT_TABLE_ModifiedBy]  DEFAULT ((-1)) FOR [ModifiedBy]
GO

ALTER TABLE [dbo].[MASTER_ACCOUNT_TABLE] ADD  CONSTRAINT [DF_MASTER_ACCOUNT_TABLE_isEnabled]  DEFAULT ((1)) FOR [isEnabled]
GO


